# Description
# -----------
# This workflow builds and releases the maven artifact
#
# Setup
# -----
# 1. Create the following secrets inside GitHub:
#    - LMS_MAVEN_SETTINGS (Base64 encoded settings.xml file)
#    - LMS_MAVEN_SECURITY (Base64 encoded settings-security.xml file)
#    - LMS_GPG_PASSPHRASE (GPG passphrase)
#    - LMS_GPG_PRIVATE_KEY (GPG private key to be imported)
#    - LMS_GIT_CONFIG (Base64 encoded .gitconfig file)

name: Maven Release

on:
  workflow_dispatch:

jobs:
  release:
    uses: indiana-university/lms-githubaction-library/.github/workflows/release.yml@v1
    with:
      java_version: 25
      full_maven_release: true
    secrets:
      LMS_MAVEN_SETTINGS: ${{ secrets.LMS_MAVEN_SETTINGS }}
      LMS_MAVEN_SECURITY: ${{ secrets.LMS_MAVEN_SECURITY }}
      LMS_GPG_PASSPHRASE: ${{ secrets.LMS_GPG_PASSPHRASE }}
      LMS_GPG_PRIVATE_KEY: ${{ secrets.LMS_GPG_PRIVATE_KEY }}
      LMS_GIT_CONFIG: ${{ secrets.LMS_GIT_CONFIG }}
